# Generated by Django 5.1.2 on 2024-10-13 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_rename_tegs_quote_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
