# Generated by Django 5.1.2 on 2024-10-16 17:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_alter_quote_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
